### ISSUE TITLE
fails to recognize import glob from '@rollup/plugin-glob'

### ISSUE THREAD

**Issue by actionableinsights** [joshnuss/sample-blog#1]
import glob from '@rollup/plugin-glob'

@ my-sappper-app % yarn dev                      
yarn run v1.22.4
warning package.json: No license field
$ sapper dev
(node:99386) UnhandledPromiseRejectionWarning: Error: Cannot find module '@rollup/plugin-glob@1.0.2'

**Comment by joshnuss** [comment]
Hi @actionableinsights,

The npm package should be `rollup-plugin-glob`. (not `@rollup/plugin-glob`)

There was a typo in the YouTube video. 

Let me know if that fixes it for you

**Comment by joshnuss** [comment]
Closing. Feel free to re-open if it's still an issue.

**Comment by actionableinsights** [comment]
thanks!
