### ISSUE TITLE
Posts on the root route

### ISSUE THREAD

**Issue by gurugeek** [joshnuss/sample-blog#5]
Thanks a lot for your screencasts and the sample. I tried ot and all works fine but just one issue about the paths. Is there a way to avoid using a s second level path /posts for the posts ?

I would like to have the articles to be directly on the main route e.g. (/my-new-article  not /posts/my-new-article)and I am not sure how this can be achieved without intrfering with the other routes in sapper.  Thanks in advance for your help.

**Comment by joshnuss** [comment]
Hi @gurugeek,

Glad you found it helpful.

To make that work, you can move the `posts/[permalink].svelte` file to the root.

```
git mv src/routes/posts/\[permalink.svelte\] src/routes/
```

Then update URLs in `PostList.svelte`:

```diff
---<a href={`/posts/${post.permalink}`}>
+++<a href={`/${post.permalink}`}>
```

**Comment by gurugeek** [comment]
awesome! this worked fine thank you for the prompt reply :) I think is very useful. It looks way cleaner !
