### ISSUE TITLE
tags not always working?

### ISSUE THREAD

**Issue by gurugeek** [joshnuss/sample-blog#6]
Hi again 👍 I did add tags to my posts and followed the tutorial but it seems not to be working as intended: you can see it at 

https://sv.html.dev 
or https://sv.html.dev/tag/html   the css post appears under html and the other way around

on the .md files I have something like:
---
title: Introduction to CSS
date: 2020-12-21
summary: HTML and CSS are both essential in frontend web design
tags: css
humandate: 28 Dez 2020
---
---
title: Introduction to HTML
date: 2020-12-21
tags: html
summary: In this mini course provided by Scrimba you can get started with HTML
humandate: 28 Dez 2020
---

not consistent in terms of order I know. I wonder if this is what causes the bug ?

**Comment by joshnuss** [comment]
Hi @gurugeek,

Thanks for reporting!

It was a bug, the `posts.filter()` logic was inverted. It's fixed now.

Let me know if you run into any other issues.

**Comment by gurugeek** [comment]
Ah right ! it was inverted ! Works fine now ! thanks for the fix :) 💯
